### ISSUE TITLE
About text encoder

### ISSUE THREAD

**Issue by zyn213** [lxa9867/R2VOS#3]
Hi! May I ask why you chose Roberta as your text encoder? Why didn't you use the text encoder from CLIP or Bert? Thank you!

**Comment by lxa9867** [comment]
Thanks for your interest. We select Roberta following the referformer for a fair comparison. 

We did try clip text encoder while we didn’t find a significant performance improvement in our experiments.

**Comment by zyn213** [comment]
I see. Thank you so much!
